<?php
/**
 * QR indexer — append a QR code under every post / page that encodes
 * the current permalink.
 *
 * @package BSPE\Connect
 */

namespace BSPE\Connect;

defined( 'ABSPATH' ) || exit;

/**
 * Hooks the_content to append a `<p id="qri-code">` block containing
 * an <a> wrapping an <img>, where the image is a QR code generated by
 * quickchart.io for the current permalink. The anchor href is the
 * same permalink so:
 *   - hovering on desktop shows the URL (browser status bar + title)
 *   - clicking on desktop opens the page itself
 *   - scanning with a phone camera gives the same URL out of the QR
 *
 * Implementation note: we switched back to quickchart.io after the
 * self-hosted JS encoder shipped in v3.1.0 - v3.1.2 produced
 * structurally-valid QR codes that real-world phone cameras still
 * refused to scan reliably. The external service is rock-solid in
 * practice; the trade-offs (privacy leak of post URLs to quickchart,
 * external availability dependency) are accepted for now and can be
 * revisited later if a vetted self-hosted alternative arrives.
 *
 * Safety notes for the <img> choice over <iframe>:
 *   - <img> can't execute JS, can't navigate the parent page
 *   - <iframe> would also be sandboxable, but <img> is strictly less
 *     dangerous when consuming third-party content
 *   - referrerpolicy="no-referrer" stops the visitor's URL from
 *     leaking to quickchart.io via the Referer header
 *
 * NOTE: loading="lazy" is intentionally NOT used — it has been seen
 * to conflict with site-level image-optimization plugins (WP Rocket,
 * Smush, etc.) that also rewrite img tags. Browsers fetch this one
 * tiny image eagerly without any noticeable cost.
 *
 * Toggle:    utilities.qr_indexer        (default ON)
 * Size:      utilities.qr_size_px        (default 150, range 80-400)
 * Max width: utilities.qr_max_width_px   (default 1240, range 320-2400)
 */
final class QR_Indexer {

	public const HANDLE_CSS = 'bspe-connect-qr-indexer';

	/**
	 * QR-as-an-image endpoint. Returns a PNG. Plenty of free QR
	 * services would work; quickchart was BSPE's original choice.
	 */
	private const SERVICE_BASE = 'https://quickchart.io/chart';

	public static function init(): void {
		if ( ! (bool) Settings::get( 'utilities.qr_indexer', true ) ) {
			return;
		}

		add_filter( 'the_content', [ self::class, 'append_qr' ], 99 );
		add_action( 'wp_enqueue_scripts', [ self::class, 'enqueue_assets' ] );
	}

	/**
	 * Append the QR wrapper to the post body. Two guards keep this from
	 * firing where it shouldn't:
	 *   - is_singular() — we only want the QR on standalone post / page
	 *     views, not on archive / category / search index pages.
	 *   - in_the_loop() + main query — defends against shortcode / widget
	 *     renders of post content that would otherwise duplicate the QR.
	 */
	public static function append_qr( string $content ): string {
		if ( ! is_singular() ) {
			return $content;
		}
		if ( ! in_the_loop() || ! is_main_query() ) {
			return $content;
		}

		$url = get_permalink();
		if ( ! $url ) {
			return $content;
		}
		$size = (int) Settings::get( 'utilities.qr_size_px', 150 );
		$size = max( 80, min( 400, $size ) );

		$qr_src = add_query_arg(
			[
				'cht' => 'qr',
				'chs' => $size . 'x' . $size,
				'chl' => rawurlencode( $url ),
			],
			self::SERVICE_BASE
		);

		$wrapper = sprintf(
			'<p id="qri-code"><a href="%1$s" title="%1$s" class="bspe-qri-link" rel="bookmark"><img src="%2$s" alt="%3$s" width="%4$d" height="%4$d" referrerpolicy="no-referrer" /></a></p>',
			esc_url( $url ),
			esc_url( $qr_src ),
			esc_attr__( 'QR code for this page', 'bspe-connect' ),
			$size
		);
		return $content . $wrapper;
	}

	public static function enqueue_assets(): void {
		if ( ! is_singular() ) {
			return;
		}

		wp_enqueue_style(
			self::HANDLE_CSS,
			BSPE_CONNECT_URL . 'public/assets/qr-indexer.css',
			[],
			BSPE_CONNECT_VERSION
		);

		// Emit the max-width as a CSS custom property — keeps the
		// stylesheet static while letting the WP setting drive layout.
		$max_width = (int) Settings::get( 'utilities.qr_max_width_px', 1240 );
		$max_width = max( 320, min( 2400, $max_width ) );
		wp_add_inline_style(
			self::HANDLE_CSS,
			'#qri-code { --bspe-qri-max-width: ' . $max_width . 'px; }'
		);
	}
}
